title: 跟鬼哥一起学LLM
author: luoli

exclude_patterns:
  - .venv
  - "**.ipynb_checkpoints"
  - _build

execute:
  execute_notebooks: "off"

parse:
  myst_enable_extensions:
    - colon_fence

html:
  use_repository_button: true
  use_issues_button: true
  extra_css:
    - _static/custom.css
  extra_javascript:
    - _static/custom.js

sphinx:
  config:
    copyright: "2026"
    html_logo: _static/guige.jpg

repository:
  url: https://github.com/luoli523/learn-llm
  branch: main
